<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>


    <PackageId>Sentinel.Analytics.Client</PackageId>
    <Version>1.0.0</Version>
    <Authors>Aleh</Authors>
    <Company>LATec</Company>
    <Description>Sentinel Analytics SDK for .NET MAUI</Description>
    <RepositoryUrl>https://github.com/yourrepo/sentinel-analytics</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Core" Version="10.0.31" />
  </ItemGroup>
</Project>
