using System.Runtime.Serialization;

namespace SentinelAnalytics.Maui;

//
// Summary:
//     Exception type thrown for testing purposes. See Microsoft.AppCenter.Crashes.Crashes.GenerateTestCrash.
[Serializable]
public class TestCrashException : Exception
{
    //
    // Summary:
    //     Initializes a new instance of the TestCrashException class with a predefined
    //     error message.
    public TestCrashException()
        : base("Test crash exception generated by SDK")
    {
    }

    //
    // Summary:
    //     Deserialization constructor. Not intended for public use.
    protected TestCrashException(SerializationInfo info, StreamingContext context)
        : base(info, context)
    {
    }
}